// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-CoebXd0IHt0GUB5pGtxIkwr-R76bnek',
    appId: '1:1055783885683:web:aca9e00a105b8421b4c306',
    messagingSenderId: '1055783885683',
    projectId: 'chat-ab761',
    authDomain: 'chat-ab761.firebaseapp.com',
    storageBucket: 'chat-ab761.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbqPZ5Ebc4qV7fV8Q5kbR6vRmqd8_-r8A',
    appId: '1:1055783885683:android:b138138b06f52663b4c306',
    messagingSenderId: '1055783885683',
    projectId: 'chat-ab761',
    storageBucket: 'chat-ab761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYwmb_n3h5KLnf_2h6j84cdtkzoH1YCAU',
    appId: '1:1055783885683:ios:1731c7174c2ea846b4c306',
    messagingSenderId: '1055783885683',
    projectId: 'chat-ab761',
    storageBucket: 'chat-ab761.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYwmb_n3h5KLnf_2h6j84cdtkzoH1YCAU',
    appId: '1:1055783885683:ios:1731c7174c2ea846b4c306',
    messagingSenderId: '1055783885683',
    projectId: 'chat-ab761',
    storageBucket: 'chat-ab761.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-CoebXd0IHt0GUB5pGtxIkwr-R76bnek',
    appId: '1:1055783885683:web:81cd226faefc865fb4c306',
    messagingSenderId: '1055783885683',
    projectId: 'chat-ab761',
    authDomain: 'chat-ab761.firebaseapp.com',
    storageBucket: 'chat-ab761.firebasestorage.app',
  );
}
